resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: my-github-repo
  type: git
  source:
    uri: ((my_github_repo))
    branch: master

- name: cf-env
  type: cf-cli-resource
  source:
    api: ((cf_api))
    username: ((cf_login))
    password: ((cf_password))
    org: ((cf_org))
    space: ((cf_space))
    skip_cert_check: true

jobs:
- name: hello-world
  public: true
  plan:
  - get: my-github-repo
    trigger: true
  - put: cf-push
    resource: cf-env
    params:
      command: push
      app_name: ((my_app_name))
      memory: 128M
      path: ((my_app_path))
      buildpack: ((cf_buildpack))
